name: Docker CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./food-delivery-backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/food-delivery-backend:latest

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./food-delivery-frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/food-delivery-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/food-delivery-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/food-delivery-frontend:latest

            docker stop backend || true && docker rm backend || true
            docker stop frontend || true && docker rm frontend || true

            docker run -d --name backend -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/food-delivery-backend:latest
            docker run -d --name frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/food-delivery-frontend:latest
